stella_adjoint_all: vmec modules stella_adjoint

stella_adjoint: $(stella_adjoint_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

stella_adjoint.x: $(stella_adjoint_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

.PHONY: modules utils_all geo_all vmec

modules: utils.a geo.a

### UTILS
utils_all: utils.a

UTIL_OBJ = spl.o constants.o file_utils.o netcdf_utils.o command_line.o
utils.a: $(UTIL_OBJ)
	$(ARCH) $(ARCHFLAGS) $@ $^
	$(RANLIB) $@

### VMEC interface
vmec:
	$(MAKE) -C $(VMEC)

### GEO
geo_all: vmec geo.a

GEO_OBJ = stella_geometry.o inputprofiles_interface.o millerlocal.o vmec_geo.o

geo.a: $(GEO_OBJ)
	$(ARCH) $(ARCHFLAGS) $@ $^
	$(RANLIB) $@

distclean:
	-rm -f stella_adjoint stella_adjoint.x
